apiVersion: v1
kind: Pod
metadata:
  name: http-readiness-pod
  labels:
    type: pod
spec:
  volumes:
    - name: http-vol
      emptyDir: {}
  containers:
    - name: http-readiness-pod
      image: angelgoez/api-readiness-socket
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: http-vol
          mountPath: /http-vol
      readinessProbe:
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        httpGet:
          port: 8080
          path: /healthcheck
