apiVersion: v1
kind: Pod
metadata:
  name: socket-readiness-pod
  labels:
    type: pod
spec:
  volumes:
    - name: socket-vol
      emptyDir: {}
  containers:
    - name: socket-readiness-pod
      image: angelgoez/api-readiness-socket
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: socket-vol
          mountPath: /socket-vol
      readinessProbe:
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        tcpSocket:
          port: 8080
