apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
  labels:
    strategy: init-container
spec:
  restartPolicy: Always
  initContainers:
    - image: busybox
      name: initial
      imagePullPolicy: Always
      command:
        - "sh"
        - "-c"
        - "echo Iniciando el contenedor; sleep 20; echo Inicializacion completada."
  containers:
    - image: nginx
      name: nginx
      imagePullPolicy: Always
      ports:
        - containerPort: 80
