---
apiVersion: v1
kind: Pod
metadata:
  name: prod-database
  labels:
    kind: pod
    database: prod-database
spec:
  containers:
    - image: mongo:4.2.9
      name: prod-database
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: toor
...
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-database
  labels:
    kind: pod
    database: dev-database
spec:
  containers:
    - name: dev-database
      image: mongo:4.2.9
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root_dev
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: toor_dev
...
---
apiVersion: v1
kind: Service
metadata:
  name: prod-database-cluster-ip-service
  labels:
    kind: service
spec:
  selector:
    database: prod-database
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: prod-database-port
...
---
apiVersion: v1
kind: Service
metadata:
  name: dev-database-cluster-ip-service
  labels:
    kind: service
spec:
  selector:
    database: dev-database
  type: ClusterIP
  ports:
    - name: dev-database-port
      targetPort: 27017
      port: 27017
      protocol: TCP








