apiVersion: batch/v1
kind: Job
metadata:
  name: random-failure-job-parallelism
  labels:
    kind: job
spec:
  completions: 5
  parallelism: 5
  template:
    metadata:
      name: random-failure-pod-parallelism
    spec:
      restartPolicy: OnFailure
      containers:
        - image: angelgoez/random-failure
          name: random-failure-container-parallelism
          imagePullPolicy: Always
