---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    engine: mongodb
    app: database
spec:
  volumes:
    - name: vol2
      emptyDir: {}
  containers:
    - image: mongo:4.2.9
      name: database
      resources: {}
      env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: toor
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
      volumeMounts:
        - name: vol2
          mountPath: /data/db
      ports:
        - containerPort: 27017
...
---
apiVersion: v1
kind: Service
metadata:
  name: database-cluster-ip-service
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo-db
