apiVersion: v1
kind: Pod
metadata:
  name: two-container-pod
spec:
  containers:
    - image: nginx
      name: frontend
      resources: {}
      ports:
        - containerPort: 80
    - image: busybox
      name: tester
      resources: {}
      command:
        - "/bin/sh"
        - "-c"
        - "sleep 99999;"
